import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translations
const translations = {
  de: {
    menu: {
      login: 'Anmelden',
      logout: 'Abmelden',
      account: 'Konto',
      profile: 'Profil',
      faq: 'FAQ',
      prices: 'Preise',
      support: 'Support',
      legal: 'Rechtliches',
      imprint: 'Impressum',
      back: 'Zurück',
    },
    hero: {
      claim: 'From Delay to Pay',
      title: 'Bahnverspätung?\nHol dir dein Geld zurück!',
      mobileTitle: 'Bahnverspätung?\nHol dir dein Geld zurück!',
      sub: 'Du musst dich nicht durch Formulare kämpfen. RailBack prüft deine Reise, zeigt dir deinen möglichen Anspruch und führt dich bis zur Auszahlung.',
      mobileSub: 'Ticket hochladen, Verspätung prüfen und Entschädigung erhalten.',
      cta1: 'Lass dich entschädigen!',
      mobileCta: 'Jetzt Anspruch prüfen',
      cta2: 'Wann bekomme ich Geld?',
      tag: ['EINFACH.', 'DIGITAL.', 'STRESSFREI.'],
      proof: [
        'Lade dein Ticket hoch',
        'Die Verspätung wird geprüft',
        'Erhalte deine Entschädigung',
      ],
      trust: [
        'Kein Antrag ohne deine Freigabe',
        'Antrag in unter 60 Sekunden',
        'DSGVO-konform aus Mannheim',
      ],
      phone: {
        greeting: 'Hallo Tobias!',
        overview: 'Hier ist dein Reiseüberblick.',
        route: 'München → Berlin',
        meta: '24.06.2026 • ICE 1232',
        amount: '24,50 €',
        amountLabel: 'Erwartete Entschädigung',
        delay: 'Verspätung erkannt · 78 Min',
        ticketChecked: 'Ticket geprüft',
        claimCalculated: 'Anspruch berechnet',
        refundPossible: 'Erstattung möglich',
        refundBasis: 'Basierend auf Ticketpreis und erkannter Verspätung.',
      },
    },
    eligibility: {
      title: 'Wenn die Bahn dich warten lässt, muss es nicht bei Ärger bleiben.',
      lead: 'Die Höhe hängt von Verspätung, Ticketpreis und Reisesituation ab. RailBack zeigt dir vor dem Antrag, was realistisch möglich ist.',
      items: [
        {
          amount: '25%',
          title: 'Ab 60 Minuten am Ziel',
          text: 'Bei vielen Bahnreisen kann ab einer Stunde Verspätung ein Teil des Ticketpreises erstattet werden.',
        },
        {
          amount: '50%',
          title: 'Ab 120 Minuten am Ziel',
          text: 'Bei sehr langen Verzögerungen kann der Anspruch deutlich höher ausfallen.',
        },
        {
          amount: 'Prüfung',
          title: 'Ausfall oder Anschluss verpasst',
          text: 'Auch Zugausfälle und verpasste Anschlüsse können relevant sein. Wir prüfen die konkrete Reise.',
        },
        {
          amount: 'Klarheit',
          title: 'Vorher wissen, ob es sich lohnt',
          text: 'Du siehst den möglichen Betrag und die Bedingungen, bevor ein Antrag rausgeht.',
        },
      ],
    },
    faq: {
      title: 'Häufig gestellte Fragen',
      lead: 'Hier findest du Antworten auf die wichtigsten Fragen rund um RailBack und Bahnerstattungen.',
      topics: [
        { id: 'ticket', t: 'Ticket & Upload', d: 'Wie du dein Ticket hinzufügst und was wir unterstützen', icon: 'ticket' },
        { id: 'reise', t: 'Reise & Verspätung', d: 'Wie die Prüfung läuft und ab wann du Anspruch hast', icon: 'clock' },
        { id: 'anspruch', t: 'Anspruch & Erstattung', d: 'Wie die Berechnung funktioniert und was du erwarten kannst', icon: 'euro' },
        { id: 'antrag', t: 'Antrag & Auszahlung', d: 'Was nach der Freigabe passiert und wann du dein Geld bekommst', icon: 'checkCircle' },
      ],
    },
    footer: {
      tagline: 'From Delay to Pay.',
      copyright: '© 2026 Elaspix UG · Alle Rechte vorbehalten.',
    },
    auth: {
      login: {
        title: 'Willkommen zurück',
        subtitle: 'Melde dich an, um deine Anträge zu sehen.',
        email: 'E-Mail',
        password: 'Passwort',
        submit: 'Einloggen',
        noAccount: 'Noch kein Konto?',
        register: 'Jetzt registrieren',
        error: 'E-Mail oder Passwort passen nicht. Bitte prüfe deine Angaben.',
        invalid: 'E-Mail oder Passwort passen nicht. Bitte prüfe deine Angaben.',
        suspended: 'Dieses Konto ist gesperrt. Bitte wende dich an den Support.',
        deletionScheduled: 'Dieses Konto wird gelöscht. Ein neuer Login ist nicht möglich.',
        network: 'Verbindung zum Server fehlgeschlagen. Bitte versuche es erneut.',
      },
      register: {
        title: 'Konto anlegen',
        subtitle: 'Ein paar Angaben — dann kannst du direkt deinen ersten Antrag stellen.',
        step1Title: 'Persönliche Daten',
        step2Title: 'Adresse',
        step3Title: 'Bankdaten',
        step4Title: 'Bestätigung',
        vorname: 'Vorname',
        nachname: 'Nachname',
        email: 'E-Mail',
        password: 'Passwort',
        telefon: 'Telefon',
        strasse: 'Straße',
        hausnr: 'Hausnummer',
        plz: 'PLZ',
        ort: 'Ort',
        land: 'Land',
        iban: 'IBAN',
        bic: 'BIC',
        skipBank: 'Später hinzufügen',
        datenschutzPrefix: 'Ich akzeptiere die ',
        datenschutzLink: 'Datenschutzerklärung',
        agbPrefix: 'Ich akzeptiere die ',
        agbLink: 'AGB',
        next: 'Weiter',
        back: 'Zurück',
        submit: 'Registrieren',
        haveAccount: 'Bereits ein Konto?',
        login: 'Anmelden',
        error: 'Hier ist etwas schiefgelaufen. Bitte prüfe deine Angaben und versuche es nochmal.',
        emailTaken: 'Diese E-Mail ist bereits registriert. Bitte melde dich an.',
        validation: 'Einige Angaben sind ungültig. Bitte prüfe die markierten Felder.',
        network: 'Verbindung zum Server fehlgeschlagen. Bitte versuche es erneut.',
      },
      profile: {
        title: 'Profil',
        subtitle: 'Deine Daten, immer aktuell. Wir nutzen sie nur für deine Anträge und Auszahlungen.',
        personalTitle: 'Persönliche Daten',
        bankTitle: 'Bankdaten',
        accountTitle: 'Konto',
        edit: 'Bearbeiten',
        save: 'Speichern',
        cancel: 'Abbrechen',
        deleteAccount: 'Konto löschen',
        deleteConfirm: 'Möchtest du dein Konto wirklich löschen? Deine Anträge und Verlaufsdaten werden dabei ebenfalls gelöscht — das lässt sich nicht rückgängig machen.',
        confirmPassword: 'Passwort bestätigen',
        updateSuccess: 'Erfolgreich aktualisiert',
        updateError: 'Aktualisierung fehlgeschlagen',
        loading: 'Lädt …',
        loadError: 'Deine Daten konnten nicht geladen werden. Bitte versuche es erneut.',
      },
    },
    dashboard: {
      heroTitle: 'Bahnverspätung? Wir helfen bei der Entschädigung!',
      heroSub: 'Lade dein Ticket hoch, lass die Verspätung prüfen und erhalte einen vorbereiteten Antrag für deine Entschädigung.',
      startCta: 'Erstattung starten',
      claimsTitle: 'Anträge',
      details: 'Details',
      date: 'Datum',
      trip: 'Reise',
      traveler: 'Reisende',
      expected: 'Erwartet',
      claimFallbackTitle: 'Antrag',
      empty: 'Noch keine Anträge — starte oben deine erste Erstattung.',
      loading: 'Anträge werden geladen …',
      loadError: 'Anträge konnten nicht geladen werden.',
      faq: 'FAQ',
      help: 'Hilfe',
      menu: 'Anträge',
    },
    claimDetail: {
      back: 'Zurück zur Übersicht',
      updated: 'Zuletzt aktualisiert',
      claim: 'Antrag',
      antragsart: 'Antragsart',
      antragsgrund: 'Grund',
      delay: 'Verspätung',
      expectedRefund: 'Erwartete Erstattung',
      trip: 'Reise',
      date: 'Datum',
      route: 'Strecke',
      train: 'Zug',
      scheduled: 'Plan',
      actual: 'Tatsächlich',
      delayedTag: 'verspätet',
      ticketPrice: 'Ticketpreis',
      traveler: 'Reisende',
      name: 'Name',
      email: 'E-Mail-Versand',
      emailStatus: 'Status',
      submittedAt: 'Eingereicht am',
      timeline: 'Zeitverlauf',
      loading: 'Antrag wird geladen …',
      loadError: 'Antrag konnte nicht geladen werden.',
      notFound: 'Diesen Antrag gibt es nicht (oder er gehört nicht zu deinem Konto).',
      fullId: 'Vorgangs-ID',
      copied: 'Kopiert',
      dangerTitle: 'Antrag löschen',
      deleteHint: 'Solange dein Antrag noch nicht abgeschickt wurde, kannst du ihn hier entfernen. Die Daten werden dauerhaft gelöscht.',
      deleteAction: 'Antrag löschen',
      deleteConfirmHint: 'Sicher? Dieser Antrag wird endgültig gelöscht und lässt sich nicht wiederherstellen.',
      deleteConfirm: 'Ja, löschen',
      deleteCancel: 'Abbrechen',
      deleting: 'Wird gelöscht …',
      deleteError: 'Der Antrag konnte nicht gelöscht werden.',
    },
    wizard: {
      back: 'Zurück',
      next: 'Weiter',
      ticketArt: {
        title: 'Was für ein Ticket ist es?',
        sub: 'Damit wir dich direkt in den passenden Antrag führen.',
        einzelTitle: 'Einzelfahrkarte',
        einzelBody: 'Eine einzelne Fahrt — ICE, IC, RE, Sparpreis, Flexpreis …',
        zeitkarteTitle: 'Zeitkarte / Deutschland-Ticket',
        zeitkarteBody: 'Abo, Monats- oder Wochenkarte. Keine Ticketnummer nötig — lade einfach dein Ticket hoch.',
      },
      entry: {
        title: 'Antrag starten',
        sub: 'Wähle den Weg, der für dich am schnellsten ist.',
        uploadTitle: 'Ticket hochladen',
        uploadBody: 'Wir lesen die Daten automatisch aus deinem Ticket.',
        lookupTitle: 'Fahrt suchen',
        lookupBody: 'Für Vielfahrer: schnell den passenden Zug wählen.',
        manualTitle: 'Manuell eingeben',
        manualBody: 'Alle Daten selbst eintragen — auch ohne Ticket.',
      },
      upload: {
        title: 'Ticket hochladen',
        titleZeitkarte: 'Deutschland-Ticket hochladen',
        hint: 'Lade dein Ticket hoch — wir lesen die Daten automatisch für dich aus.',
        hintZeitkarte: 'Lade dein Deutschland-Ticket als Nachweis hoch (PDF oder Screenshot). Die Reisedaten trägst du im nächsten Schritt selbst ein.',
        pick: 'Datei auswählen',
        formats: 'PDF, JPG oder PNG',
        formatsZeitkarte: 'Nur PDF',
        maxSize: 'Maximale Dateigröße: {mb} MB',
        removeFile: 'Datei entfernen',
        processing: 'Wir lesen dein Ticket aus…',
        processingHint: 'Wir übernehmen deine Reisedaten automatisch.',
        presigning: 'Upload wird vorbereitet …',
        uploading: 'Ticket wird hochgeladen …',
        confirming: 'Upload wird bestätigt …',
        extracting: 'Daten werden ausgelesen …',
        errBadType: 'Nur PDF, JPG oder PNG erlaubt.',
        errBadTypeZeitkarte: 'Für das Deutschland-Ticket bitte nur PDF hochladen.',
        errTooLarge: 'Datei zu groß (max. 10 MB).',
        errGeneric: 'Der Upload ist fehlgeschlagen. Bitte versuche es erneut.',
        outcomeFilled: '✓ Wir haben deine Reisedaten übernommen. Bitte prüfe sie auf der nächsten Seite.',
        outcomeZeitkarte: '✓ Dein Deutschland-Ticket ist hochgeladen. Trage im nächsten Schritt die Daten deiner verspäteten Fahrt ein.',
        outcomeEmpty: 'Aus deinem Ticket konnten wir keine Reisedaten auslesen — meistens liegt es am Barcode. Bitte trage die Daten im nächsten Schritt manuell ein.',
        outcomeFailed: 'Das automatische Auslesen ist fehlgeschlagen. Bitte trage die Daten im nächsten Schritt manuell ein.',
        outcomeTimeout: 'Das Auslesen dauert länger als erwartet. Du kannst deine Daten schon manuell eintragen — wir übernehmen die Barcode-Daten später automatisch.',
        continueManually: 'Manuell weiter',
        enterManually: 'Manuell eingeben',
      },
      lookup: {
        title: 'Fahrt suchen',
        hint: 'Suche die Fahrt, für die du Erstattung möchtest. Wir zeigen dir die Verspätungsdaten aus dem Bahnarchiv.',
        from: 'Startbahnhof',
        to: 'Zielbahnhof',
        date: 'Reisedatum',
        aroundTime: 'Uhrzeit (ungefähr)',
        aroundTimeHelper: 'Optional — Planabfahrt laut Ticket. Leer lassen zeigt alle Züge des Tages.',
        swap: 'Start und Ziel tauschen',
        search: 'Suchen',
        searching: 'Wird gesucht …',
        resultsTitle: 'Verbindungen',
        pickHint: 'Wähle die Fahrt, die du tatsächlich genommen hast.',
        widenedNote: 'Um deine Uhrzeit haben wir nichts gefunden — hier alle Züge des Tages.',
        onTime: 'Pünktlich gefahren',
        minutesLate: 'Min. Verspätung',
        cancelled: 'Zug ausgefallen',
        actual: 'Tatsächlich',
        skipToManual: 'Manuell weiter',
        noResultsTitle: 'Keine passenden Verbindungen',
        noResultsHint:
          'Für dieses Datum und diese Route haben wir keine Direktverbindung im Archiv. Probier ein anderes Zeitfenster oder trag die Fahrt manuell ein.',
        qualityFull: 'Live-Daten',
        qualityPartial: 'Teilweise Live',
        qualityPlan: 'Nur Plan-Daten',
        errBadFrom: 'Startbahnhof nicht gefunden.',
        errBadTo: 'Zielbahnhof nicht gefunden.',
        errGeneric: 'Die Suche ist fehlgeschlagen. Bitte versuche es erneut.',
      },
      reise: {
        title: 'Reisedaten prüfen',
        from: 'Startbahnhof',
        to: 'Zielbahnhof',
        date: 'Reisedatum',
        train: 'Zugnummer',
        trainCategory: 'Zug-Art',
        trainCategoryEmpty: '– wählen –',
        trainCategoryOther: 'Sonstige',
        plannedDeparture: 'Geplante Abfahrtszeit',
        plannedArrival: 'Geplante Ankunftszeit',
        required: 'Pflichtfeld',
        missingSummary: 'Es fehlen noch Angaben. Bitte fülle die rot markierten Felder aus.',
        ticketNumber: 'Ticketnummer',
        ticketPrice: 'Ticketpreis (EUR)',
        priceHint: '',
        priceFormat: 'Bitte eine gültige Zahl eingeben — z.B. 29,90 oder 29.90.',
      },
      problem: {
        title: 'Verspätung oder Problem',
        question: 'Was ist passiert?',
        reiseabbruch: 'Ich bin unterwegs ausgestiegen',
        reiseunterbrechung: 'Ich habe die Fahrt kurz unterbrochen',
        verpassterAnschluss: 'Ich habe einen Anschluss verpasst',
        letzterUmstieg: 'Ich bin am letzten Umstieg hängengeblieben',
        verspaetung: 'Mein Zug hatte Verspätung',
        ausfall: 'Mein Zug ist ausgefallen',
        missedBahnhofLabel: 'An welchem Bahnhof hast du den Anschluss verpasst?',
        autoCheck: 'Verspätung automatisch prüfen',
        autoChecking: 'Wird geprüft …',
        autoCheckResult: 'Verspätung: +{minutes} min · Ausfall: {cancelled}',
        autoCheckError: 'Verspätungsdaten konnten nicht geladen werden.',
        grundRequired: 'Bitte wähle mindestens einen Grund aus.',
      },
      person: {
        title: 'Deine Kontaktdaten',
        fullName: 'Vor- und Nachname',
        email: 'E-Mail-Adresse',
        telefonOpt: 'Telefonnummer (optional)',
        kundennummerOpt: 'Kundennummer (optional)',
        kundennummerHelper: 'Nur für dein Profil — wird derzeit nicht an die Bahn übermittelt.',
      },
      auszahlung: {
        title: 'Wohin dürfen wir dein Geld schicken?',
        kontoinhaber: 'Kontoinhaber',
        iban: 'IBAN',
        bic: 'BIC',
        note: 'Sobald die Bahn deinen Antrag bestätigt, überweisen wir dir das Geld.',
        ibanInvalid: 'Diese IBAN sieht nicht korrekt aus. Bitte prüfe deine Eingabe.',
        bicInvalid: 'Diese BIC sieht nicht korrekt aus (8 oder 11 Zeichen).',
      },
      review: {
        title: 'Bitte prüf deine Angaben',
        edit: 'Bearbeiten',
        ticket: 'Ticket',
        trip: 'Reise',
        problem: 'Problem',
        person: 'Persönliche Daten',
        payout: 'Auszahlung',
        noTicket: 'Kein Ticket hochgeladen',
        submit: 'Antrag absenden',
        submittingLabel: 'Wird gesendet …',
        claimTypeTitle: 'Antragsart',
        suggested: 'Vorschlag basierend auf der Verspätungsprüfung: {art}',
        zeitkarteLocked: 'Als Deutschland-Ticket-Antrag ist die Antragsart automatisch auf „Entschädigung Zeitkarte" gesetzt.',
        antragstellungOrt: 'Ort der Antragstellung',
        zusaetzlicheAngaben: 'Zusätzliche Angaben (optional)',
        zusaetzlicheAngabenHint: 'z.B. Reiseabbruch, Umleitung, Details zum Anschluss (max. 2500 Zeichen)',
        belegeTitle: 'Belege für Alternativtransport',
        belegeHint: 'Bis zu 5 Belege (PDF/JPG/PNG, max. 5 MB je Datei).',
        belegeAdd: 'Beleg hinzufügen',
        belegeTyp: 'Art',
        belegeAmount: 'Betrag (EUR)',
        belegeFile: 'Datei',
        belegeRemove: 'Entfernen',
        belegeAmountFormat: 'z.B. 12,50 · 12.50 · 13',
        consentDatenschutz: 'Ich stimme der Datenschutzerklärung zu.',
        consentWahrheit: 'Ich versichere die Richtigkeit meiner Angaben.',
        consentsRequired: 'Bitte bestätige beide Erklärungen, bevor du absendest.',
        earlyStepMissing: 'Es fehlen noch Angaben aus früheren Schritten. Bitte gehe zurück und ergänze sie.',
        creatingTicket: 'Vorgang wird angelegt …',
        savingProfile: 'Profildaten werden gespeichert …',
        savingBank: 'Bankdaten werden gespeichert …',
        uploadingBelege: 'Belege werden hochgeladen …',
        submitting: 'Antrag wird eingereicht …',
        submitError: 'Der Antrag konnte nicht eingereicht werden.',
      },
      submitted: {
        title: 'Gute Nachrichten! Dein Antrag ist auf dem Weg.',
        body: 'Wir melden uns, sobald es Rückmeldung von der Bahn gibt.',
        titleWithPdfIssue: 'Antrag gespeichert — E-Mail-Versand nicht möglich',
        bodyWithPdfIssue:
          'Dein Antrag ist bei uns gespeichert, aber unser automatischer E-Mail-Versand ist gerade gestört. Wir kümmern uns darum und melden uns, sobald es weitergeht.',
        cta: 'Zur Übersicht',
        claimId: 'Vorgang',
        submittedAt: 'Eingereicht',
        expectedRefund: 'Erwartete Erstattung',
        serviceFee: 'Service-Gebühr',
        emailStatus: 'E-Mail-Status',
        emailSending: 'E-Mail wird versendet …',
        emailSent: 'E-Mail zugestellt',
        emailFailed: 'E-Mail nicht zugestellt — wir melden uns',
      },
      antragsart: {
        ERSTATTUNG_FAHRKARTE: 'Erstattung Fahrkarte',
        ENTSCHAEDIGUNG_60_119: 'Entschädigung (60–119 Min. Verspätung)',
        ENTSCHAEDIGUNG_120_PLUS: 'Entschädigung (ab 120 Min. Verspätung)',
        ENTSCHAEDIGUNG_ZEITKARTE: 'Entschädigung Zeitkarte',
        KOSTEN_ALTERNATIVTRANSPORT: 'Kosten Alternativtransport',
      },
      belegTyp: {
        TAXI: 'Taxi',
        BUS: 'Bus',
        HOTEL: 'Hotel',
        SONSTIGES: 'Sonstiges',
      },
    },
  },
  en: {
    menu: {
      login: 'Log in',
      logout: 'Log out',
      account: 'Account',
      profile: 'Profile',
      faq: 'FAQ',
      prices: 'Pricing',
      support: 'Help',
      legal: 'Legal',
      imprint: 'Imprint',
      back: 'Back',
    },
    hero: {
      claim: 'From Delay to Pay',
      title: 'Train delayed?\nGet your money back!',
      mobileTitle: 'Train delayed?\nGet your money back!',
      sub: 'Skip the paperwork maze. RailBack checks your trip, shows your possible claim and guides you through to payout.',
      mobileSub: 'Upload ticket, check delay and receive compensation.',
      cta1: 'Get compensated!',
      mobileCta: 'Check claim now',
      cta2: 'When do I get money?',
      tag: ['SIMPLE.', 'DIGITAL.', 'STRESS-FREE.'],
      proof: [
        'Upload your ticket',
        'The delay is checked',
        'Receive your compensation',
      ],
      trust: [
        'No claim without your approval',
        'Claim in under 60 seconds',
        'GDPR-compliant from Mannheim',
      ],
      phone: {
        greeting: 'Hello Tobias!',
        overview: 'Here is your trip overview.',
        route: 'Munich → Berlin',
        meta: '24 Jun 2026 • ICE 1232',
        amount: '€24.50',
        amountLabel: 'Expected compensation',
        delay: 'Delay detected · 78 min',
        ticketChecked: 'Ticket checked',
        claimCalculated: 'Claim calculated',
        refundPossible: 'Refund possible',
        refundBasis: 'Based on ticket price and detected delay.',
      },
    },
    eligibility: {
      title: 'If the railway makes you wait, frustration does not have to be the end of it.',
      lead: 'The amount depends on delay, ticket price and trip situation. RailBack shows what is realistically possible before you file.',
      items: [
        {
          amount: '25%',
          title: 'From 60 minutes at arrival',
          text: 'For many train journeys, a one-hour delay can qualify for a partial ticket refund.',
        },
        {
          amount: '50%',
          title: 'From 120 minutes at arrival',
          text: 'Very long delays can lead to a significantly higher claim.',
        },
        {
          amount: 'Check',
          title: 'Cancellation or missed connection',
          text: 'Cancelled trains and missed connections can also matter. We check your specific journey.',
        },
        {
          amount: 'Clarity',
          title: 'Know before you proceed',
          text: 'You see the possible amount and conditions before any claim is submitted.',
        },
      ],
    },
    faq: {
      title: 'Frequently Asked Questions',
      lead: 'Here you can find answers to the most important questions about RailBack and train refunds.',
      topics: [
        { id: 'ticket', t: 'Ticket & Upload', d: 'How to add your ticket and what we support', icon: 'ticket' },
        { id: 'reise', t: 'Journey & Delay', d: 'How the check works and when you are entitled to compensation', icon: 'clock' },
        { id: 'anspruch', t: 'Claim & Refund', d: 'How the calculation works and what you can expect', icon: 'euro' },
        { id: 'antrag', t: 'Application & Payout', d: 'What happens after approval and when you receive your money', icon: 'checkCircle' },
      ],
    },
    footer: {
      tagline: 'From Delay to Pay.',
      copyright: '© 2026 Elaspix UG · All rights reserved.',
    },
    auth: {
      login: {
        title: 'Welcome back',
        subtitle: 'Sign in to see your claims.',
        email: 'Email',
        password: 'Password',
        submit: 'Sign in',
        noAccount: "Don't have an account?",
        register: 'Register now',
        error: "Email or password don't match. Please check your details.",
        invalid: "Email or password don't match. Please check your details.",
        suspended: 'This account is suspended. Please contact support.',
        deletionScheduled: 'This account is scheduled for deletion. Sign-in is disabled.',
        network: 'Could not reach the server. Please try again.',
      },
      register: {
        title: 'Create account',
        subtitle: "A few details — then you're ready to file your first claim.",
        step1Title: 'Personal Information',
        step2Title: 'Address',
        step3Title: 'Bank Details',
        step4Title: 'Confirmation',
        vorname: 'First Name',
        nachname: 'Last Name',
        email: 'Email',
        password: 'Password',
        telefon: 'Phone',
        strasse: 'Street',
        hausnr: 'House Number',
        plz: 'Postal Code',
        ort: 'City',
        land: 'Country',
        iban: 'IBAN',
        bic: 'BIC',
        skipBank: 'Add Later',
        datenschutzPrefix: 'I accept the ',
        datenschutzLink: 'privacy policy',
        agbPrefix: 'I accept the ',
        agbLink: 'terms and conditions',
        next: 'Next',
        back: 'Back',
        submit: 'Register',
        haveAccount: 'Already have an account?',
        login: 'Sign in',
        error: 'Something went wrong. Please check your details and try again.',
        emailTaken: 'This email is already registered. Please sign in instead.',
        validation: 'Some fields are invalid. Please review the highlighted entries.',
        network: 'Could not reach the server. Please try again.',
      },
      profile: {
        title: 'Profile',
        subtitle: 'Your details, always up to date. We only use them for your claims and payouts.',
        personalTitle: 'Personal Information',
        bankTitle: 'Bank Details',
        accountTitle: 'Account',
        edit: 'Edit',
        save: 'Save',
        cancel: 'Cancel',
        deleteAccount: 'Delete Account',
        deleteConfirm: "Do you really want to delete your account? Your claims and history will be deleted too — this can't be undone.",
        confirmPassword: 'Confirm Password',
        updateSuccess: 'Successfully updated',
        updateError: 'Update failed',
        loading: 'Loading …',
        loadError: 'Could not load your details. Please try again.',
      },
    },
    dashboard: {
      heroTitle: 'Train delayed? We help with your compensation!',
      heroSub: 'Upload your ticket, have the delay checked, and get a prepared claim for your compensation.',
      startCta: 'Start refund',
      claimsTitle: 'Claims',
      details: 'Details',
      date: 'Date',
      trip: 'Trip',
      traveler: 'Traveler',
      expected: 'Expected',
      claimFallbackTitle: 'Claim',
      empty: 'No claims yet — start your first refund above.',
      loading: 'Loading claims …',
      loadError: 'Could not load claims.',
      faq: 'FAQ',
      help: 'Help',
      menu: 'Claims',
    },
    claimDetail: {
      back: 'Back to overview',
      updated: 'Last updated',
      claim: 'Claim',
      antragsart: 'Claim type',
      antragsgrund: 'Reason',
      delay: 'Delay',
      expectedRefund: 'Expected refund',
      trip: 'Trip',
      date: 'Date',
      route: 'Route',
      train: 'Train',
      scheduled: 'Scheduled',
      actual: 'Actual',
      delayedTag: 'delayed',
      ticketPrice: 'Ticket price',
      traveler: 'Traveler',
      name: 'Name',
      email: 'Email delivery',
      emailStatus: 'Status',
      submittedAt: 'Submitted at',
      timeline: 'Timeline',
      loading: 'Loading claim …',
      loadError: 'Could not load claim.',
      notFound: "This claim doesn't exist (or belongs to a different account).",
      fullId: 'Claim ID',
      copied: 'Copied',
      dangerTitle: 'Delete claim',
      deleteHint: "As long as your claim hasn't been submitted yet, you can remove it here. The data is deleted permanently.",
      deleteAction: 'Delete claim',
      deleteConfirmHint: 'Are you sure? This claim will be deleted permanently and cannot be recovered.',
      deleteConfirm: 'Yes, delete',
      deleteCancel: 'Cancel',
      deleting: 'Deleting …',
      deleteError: 'Could not delete this claim.',
    },
    wizard: {
      back: 'Back',
      next: 'Next',
      ticketArt: {
        title: 'What kind of ticket is it?',
        sub: "We'll route you straight into the right claim path.",
        einzelTitle: 'Single-trip ticket',
        einzelBody: 'One journey — ICE, IC, RE, Sparpreis, Flexpreis …',
        zeitkarteTitle: 'Season pass / Deutschland-Ticket',
        zeitkarteBody: "Subscription, monthly or weekly pass. No ticket number needed — just upload your pass.",
      },
      entry: {
        title: 'Start a claim',
        sub: 'Pick the fastest way for you.',
        uploadTitle: 'Upload ticket',
        uploadBody: 'We read the details from your ticket automatically.',
        lookupTitle: 'Search trip',
        lookupBody: 'For regulars — pick the right train quickly.',
        manualTitle: 'Enter manually',
        manualBody: 'Fill in every field yourself — no ticket needed.',
      },
      upload: {
        title: 'Upload ticket',
        titleZeitkarte: 'Upload Deutschland-Ticket',
        hint: "Upload your ticket — we'll read the details for you automatically.",
        hintZeitkarte: "Upload your Deutschland-Ticket as proof (PDF or screenshot). You'll enter the trip details yourself in the next step.",
        pick: 'Choose file',
        formats: 'PDF, JPG or PNG',
        formatsZeitkarte: 'PDF only',
        maxSize: 'Max file size: {mb} MB',
        removeFile: 'Remove file',
        processing: "We're reading your ticket…",
        processingHint: "We're filling in your trip details automatically.",
        presigning: 'Preparing upload …',
        uploading: 'Uploading ticket …',
        confirming: 'Confirming upload …',
        extracting: 'Reading ticket data …',
        errBadType: 'Only PDF, JPG or PNG allowed.',
        errBadTypeZeitkarte: 'For the Deutschland-Ticket, please upload a PDF only.',
        errTooLarge: 'File too large (max. 10 MB).',
        errGeneric: 'The upload failed. Please try again.',
        outcomeFilled: '✓ We filled in your trip details. Please verify them on the next screen.',
        outcomeZeitkarte: "✓ Your Deutschland-Ticket is uploaded. Enter the delayed trip's details in the next step.",
        outcomeEmpty: "We couldn't read any trip details from your ticket — usually a barcode issue. Please enter the details manually in the next step.",
        outcomeFailed: "Automatic reading failed. Please enter the details manually in the next step.",
        outcomeTimeout: "Reading is taking longer than expected. You can enter your details manually now — we'll pick up the barcode data later.",
        continueManually: 'Continue manually',
        enterManually: 'Enter manually',
      },
      lookup: {
        title: 'Search trip',
        hint: 'Find the trip you want to claim compensation for. We show the delay data from the rail archive.',
        from: 'Origin station',
        to: 'Destination station',
        date: 'Travel date',
        aroundTime: 'Time (approx.)',
        aroundTimeHelper: 'Optional — scheduled departure per your ticket. Leave empty to show all trains of the day.',
        swap: 'Swap origin and destination',
        search: 'Search',
        searching: 'Searching …',
        resultsTitle: 'Connections',
        pickHint: 'Pick the trip you actually took.',
        widenedNote: 'No matches near your time — here are all trains of the day.',
        onTime: 'Ran on time',
        minutesLate: 'min late',
        cancelled: 'Train cancelled',
        actual: 'Actual',
        skipToManual: 'Skip to manual',
        noResultsTitle: 'No matching connections',
        noResultsHint:
          'No direct connection in the archive for this date and route. Try a different time window or enter the trip manually.',
        qualityFull: 'Live data',
        qualityPartial: 'Partial live',
        qualityPlan: 'Plan only',
        errBadFrom: 'Origin station not found.',
        errBadTo: 'Destination station not found.',
        errGeneric: 'Search failed. Please try again.',
      },
      reise: {
        title: 'Check trip data',
        from: 'Origin station',
        to: 'Destination station',
        date: 'Travel date',
        train: 'Train number',
        trainCategory: 'Train type',
        trainCategoryEmpty: '– pick –',
        trainCategoryOther: 'Other',
        plannedDeparture: 'Scheduled departure time',
        plannedArrival: 'Scheduled arrival time',
        required: 'Required',
        missingSummary: 'Some details are still missing. Please fill in the fields marked in red.',
        ticketNumber: 'Ticket number',
        ticketPrice: 'Ticket price (EUR)',
        priceHint: '',
        priceFormat: 'Please enter a valid number — e.g. 29.90 or 29,90.',
      },
      problem: {
        title: 'Delay or problem',
        question: 'What happened?',
        reiseabbruch: 'I got off partway through',
        reiseunterbrechung: 'I paused my trip for a while',
        verpassterAnschluss: 'I missed a connection',
        letzterUmstieg: 'I got stuck at the last transfer',
        verspaetung: 'My train was delayed',
        ausfall: 'My train was cancelled',
        missedBahnhofLabel: 'Which station did you miss the connection at?',
        autoCheck: 'Check delay automatically',
        autoChecking: 'Checking …',
        autoCheckResult: 'Delay: +{minutes} min · Cancelled: {cancelled}',
        autoCheckError: 'Could not load delay data.',
        grundRequired: 'Please select at least one reason.',
      },
      person: {
        title: 'Your contact details',
        fullName: 'First and last name',
        email: 'Email address',
        telefonOpt: 'Phone (optional)',
        kundennummerOpt: 'Customer number (optional)',
        kundennummerHelper: 'For your profile only — not sent to Deutsche Bahn yet.',
      },
      auszahlung: {
        title: 'Where should we send your money?',
        kontoinhaber: 'Account holder',
        iban: 'IBAN',
        bic: 'BIC',
        note: "As soon as Deutsche Bahn approves your claim, we'll transfer the money.",
        ibanInvalid: "That IBAN doesn't look right. Please double-check.",
        bicInvalid: "That BIC doesn't look right (8 or 11 characters).",
      },
      review: {
        title: 'Please review your details',
        edit: 'Edit',
        ticket: 'Ticket',
        trip: 'Trip',
        problem: 'Problem',
        person: 'Personal details',
        payout: 'Payout',
        noTicket: 'No ticket uploaded',
        submit: 'Submit claim',
        submittingLabel: 'Submitting …',
        claimTypeTitle: 'Claim type',
        suggested: 'Suggested based on the delay check: {art}',
        zeitkarteLocked: 'As a Deutschland-Ticket claim, the type is automatically set to "Season-pass compensation".',
        antragstellungOrt: 'Place of application',
        zusaetzlicheAngaben: 'Additional notes (optional)',
        zusaetzlicheAngabenHint:
          'e.g. trip aborted, detour, details about the connection (max. 2500 characters)',
        belegeTitle: 'Receipts for alternative transport',
        belegeHint: 'Up to 5 receipts (PDF/JPG/PNG, max. 5 MB each).',
        belegeAdd: 'Add receipt',
        belegeTyp: 'Type',
        belegeAmount: 'Amount (EUR)',
        belegeFile: 'File',
        belegeRemove: 'Remove',
        belegeAmountFormat: 'e.g. 12.50 · 12,50 · 13',
        consentDatenschutz: 'I agree to the privacy policy.',
        consentWahrheit: 'I confirm that the information provided is accurate.',
        consentsRequired: 'Please confirm both declarations before submitting.',
        earlyStepMissing: 'Some details from earlier steps are still missing. Please go back and complete them.',
        creatingTicket: 'Creating claim …',
        savingProfile: 'Saving profile …',
        savingBank: 'Saving bank details …',
        uploadingBelege: 'Uploading receipts …',
        submitting: 'Submitting claim …',
        submitError: 'The claim could not be submitted.',
      },
      submitted: {
        title: 'Good news! Your claim is on its way.',
        body: "We'll let you know as soon as there's news from Deutsche Bahn.",
        titleWithPdfIssue: 'Claim saved — email dispatch unavailable',
        bodyWithPdfIssue:
          "Your claim is saved on our side, but our automated email dispatch is currently unavailable. We're working on it and will follow up as soon as it's fixed.",
        cta: 'Back to overview',
        claimId: 'Claim',
        submittedAt: 'Submitted',
        expectedRefund: 'Expected refund',
        serviceFee: 'Service fee',
        emailStatus: 'Email status',
        emailSending: 'Email is being sent …',
        emailSent: 'Email delivered',
        emailFailed: "Email couldn't be delivered — we'll follow up",
      },
      antragsart: {
        ERSTATTUNG_FAHRKARTE: 'Ticket refund',
        ENTSCHAEDIGUNG_60_119: 'Compensation (60–119 min delay)',
        ENTSCHAEDIGUNG_120_PLUS: 'Compensation (120+ min delay)',
        ENTSCHAEDIGUNG_ZEITKARTE: 'Season-ticket compensation',
        KOSTEN_ALTERNATIVTRANSPORT: 'Alternative-transport costs',
      },
      belegTyp: {
        TAXI: 'Taxi',
        BUS: 'Bus',
        HOTEL: 'Hotel',
        SONSTIGES: 'Other',
      },
    },
  },
};

const isLanguage = (value: string | null): value is Language => value === 'de' || value === 'en';

const getInitialLanguage = (): Language => {
  const savedLanguage = window.localStorage.getItem('rb_lang');
  return isLanguage(savedLanguage) ? savedLanguage : 'de';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem('rb_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const value = {
    lang,
    setLang: setLangState,
    t: translations[lang],
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
