import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translations
const translations = {
  de: {
    menu: {
      login: 'Anmelden',
      logout: 'Abmelden',
      account: 'Konto',
      profile: 'Profil',
      faq: 'FAQ',
      prices: 'Preise',
      support: 'Support',
      legal: 'Rechtliches',
      imprint: 'Impressum',
      back: 'Zurück',
    },
    hero: {
      claim: 'From Delay to Pay',
      title: 'Bahnverspätung?\nHol dir dein Geld zurück!',
      mobileTitle: 'Bahnverspätung?\nHol dir dein Geld zurück!',
      sub: 'Du musst dich nicht durch Formulare kämpfen. RailBack prüft deine Reise, zeigt dir deinen möglichen Anspruch und führt dich bis zur Auszahlung.',
      mobileSub: 'Ticket hochladen, Verspätung prüfen und Entschädigung erhalten.',
      cta1: 'Lass dich entschädigen!',
      mobileCta: 'Jetzt Anspruch prüfen',
      cta2: 'Wann bekomme ich Geld?',
      tag: ['EINFACH.', 'DIGITAL.', 'STRESSFREI.'],
      proof: [
        'Lade dein Ticket hoch',
        'Die Verspätung wird geprüft',
        'Erhalte deine Entschädigung',
      ],
      trust: [
        'Kein Antrag ohne deine Freigabe',
        'Antrag in unter 60 Sekunden',
        'DSGVO-konform aus Mannheim',
      ],
      phone: {
        greeting: 'Hallo Tobias!',
        overview: 'Hier ist dein Reiseüberblick.',
        route: 'München → Berlin',
        meta: '24.06.2026 • ICE 1232',
        amount: '24,50 €',
        amountLabel: 'Erwartete Entschädigung',
        delay: 'Verspätung erkannt · 78 Min',
        ticketChecked: 'Ticket geprüft',
        claimCalculated: 'Anspruch berechnet',
        refundPossible: 'Erstattung möglich',
        refundBasis: 'Basierend auf Ticketpreis und erkannter Verspätung.',
      },
    },
    eligibility: {
      eyebrow: 'Wann ist Entschädigung möglich?',
      title: 'Wenn die Bahn dich warten lässt, muss es nicht bei Ärger bleiben.',
      lead: 'Die Höhe hängt von Verspätung, Ticketpreis und Reisesituation ab. RailBack zeigt dir vor dem Antrag, was realistisch möglich ist.',
      items: [
        {
          amount: '25%',
          title: 'Ab 60 Minuten am Ziel',
          text: 'Bei vielen Bahnreisen kann ab einer Stunde Verspätung ein Teil des Ticketpreises erstattet werden.',
        },
        {
          amount: '50%',
          title: 'Ab 120 Minuten am Ziel',
          text: 'Bei sehr langen Verzögerungen kann der Anspruch deutlich höher ausfallen.',
        },
        {
          amount: 'Prüfung',
          title: 'Ausfall oder Anschluss verpasst',
          text: 'Auch Zugausfälle und verpasste Anschlüsse können relevant sein. Wir prüfen die konkrete Reise.',
        },
        {
          amount: 'Klarheit',
          title: 'Vorher wissen, ob es sich lohnt',
          text: 'Du siehst den möglichen Betrag und die Bedingungen, bevor ein Antrag rausgeht.',
        },
      ],
    },
    faq: {
      title: 'Häufig gestellte Fragen',
      lead: 'Hier findest du Antworten auf die wichtigsten Fragen rund um RailBack und Bahnerstattungen.',
      topics: [
        { id: 'ticket', t: 'Ticket & Upload', d: 'Wie du dein Ticket hinzufügst und was wir unterstützen', icon: 'ticket' },
        { id: 'reise', t: 'Reise & Verspätung', d: 'Wie die Prüfung läuft und ab wann du Anspruch hast', icon: 'clock' },
        { id: 'anspruch', t: 'Anspruch & Erstattung', d: 'Wie die Berechnung funktioniert und was du erwarten kannst', icon: 'euro' },
        { id: 'antrag', t: 'Antrag & Auszahlung', d: 'Was nach der Freigabe passiert und wann du dein Geld bekommst', icon: 'checkCircle' },
      ],
    },
    footer: {
      tagline: 'From Delay to Pay.',
      copyright: '© 2026 Elaspix UG · Alle Rechte vorbehalten.',
    },
    auth: {
      login: {
        title: 'Anmelden',
        email: 'E-Mail',
        password: 'Passwort',
        submit: 'Anmelden',
        noAccount: 'Noch kein Konto?',
        register: 'Registrieren',
        error: 'Anmeldung fehlgeschlagen',
      },
      register: {
        title: 'Registrieren',
        step1Title: 'Persönliche Daten',
        step2Title: 'Adresse',
        step3Title: 'Bankdaten',
        step4Title: 'Bestätigung',
        vorname: 'Vorname',
        nachname: 'Nachname',
        email: 'E-Mail',
        password: 'Passwort',
        telefon: 'Telefon',
        strasse: 'Straße',
        hausnr: 'Hausnummer',
        plz: 'PLZ',
        ort: 'Ort',
        land: 'Land',
        iban: 'IBAN',
        bic: 'BIC',
        skipBank: 'Später hinzufügen',
        datenschutz: 'Ich akzeptiere die Datenschutzerklärung',
        agb: 'Ich akzeptiere die AGB',
        next: 'Weiter',
        back: 'Zurück',
        submit: 'Registrieren',
        haveAccount: 'Bereits ein Konto?',
        login: 'Anmelden',
        error: 'Registrierung fehlgeschlagen',
      },
      profile: {
        title: 'Profil',
        personalTitle: 'Persönliche Daten',
        bankTitle: 'Bankdaten',
        accountTitle: 'Konto',
        edit: 'Bearbeiten',
        save: 'Speichern',
        cancel: 'Abbrechen',
        deleteAccount: 'Konto löschen',
        deleteConfirm: 'Möchtest du dein Konto wirklich löschen?',
        confirmPassword: 'Passwort bestätigen',
        updateSuccess: 'Erfolgreich aktualisiert',
        updateError: 'Aktualisierung fehlgeschlagen',
      },
    },
    dashboard: {
      heroTitle: 'Bahnverspätung? Wir helfen bei der Entschädigung!',
      heroSub: 'Lade dein Ticket hoch, lass die Verspätung prüfen und erhalte einen vorbereiteten Antrag für deine Entschädigung.',
      startCta: 'Erstattung starten',
      claimsTitle: 'Anträge',
      details: 'Details',
      date: 'Datum',
      trip: 'Reise',
      traveler: 'Reisende',
      empty: 'Noch keine Anträge — starte oben deine erste Erstattung.',
      faq: 'FAQ',
      help: 'Hilfe',
      menu: 'Anträge',
    },
    claimDetail: {
      back: 'Zurück zur Übersicht',
      updated: 'Zuletzt aktualisiert',
      claim: 'Antrag',
      antragsart: 'Antragsart',
      antragsgrund: 'Grund',
      delay: 'Verspätung',
      expectedRefund: 'Erwartete Erstattung',
      trip: 'Reise',
      date: 'Datum',
      route: 'Strecke',
      train: 'Zug',
      scheduled: 'Plan',
      actual: 'Tatsächlich',
      ticketPrice: 'Ticketpreis',
      traveler: 'Reisende',
      name: 'Name',
      email: 'E-Mail-Versand',
      emailStatus: 'Status',
      submittedAt: 'Eingereicht am',
      timeline: 'Zeitverlauf',
    },
    wizard: {
      back: 'Zurück',
      next: 'Weiter',
      entry: {
        title: 'Antrag starten',
        sub: 'Wähle, wie du deine Reise erfassen möchtest.',
        uploadTitle: 'Ticket hochladen',
        uploadBody: 'Wir lesen die Daten automatisch aus deinem Ticket.',
        lookupTitle: 'Fahrt suchen',
        lookupBody: 'Für Vielfahrer: schnell den passenden Zug wählen.',
        manualTitle: 'Manuell eingeben',
        manualBody: 'Alle Daten selbst eintragen — auch ohne Ticket.',
      },
      upload: {
        title: 'Ticket hochladen',
        hint: 'Bitte lade dein Ticket als PDF, JPG oder PNG hoch.',
        pick: 'Datei auswählen',
        formats: 'PDF, JPG oder PNG',
        maxSize: 'Maximale Dateigröße: {mb} MB',
        removeFile: 'Datei entfernen',
        processing: 'Ticket wird ausgelesen…',
        processingHint: 'Wir übernehmen deine Reisedaten automatisch.',
      },
      lookup: {
        title: 'Fahrt suchen',
        hint: 'Suche die Fahrt, für die du Erstattung möchtest. Wir zeigen dir die Verspätungsdaten aus dem Bahnarchiv.',
        from: 'Startbahnhof',
        to: 'Zielbahnhof',
        date: 'Reisedatum',
        aroundTime: 'gegen',
        search: 'Suchen',
        resultsTitle: 'Verbindungen',
        pickHint: 'Wähle die Fahrt, die du tatsächlich genommen hast.',
        onTime: 'Pünktlich gefahren',
        minutesLate: 'Min. Verspätung',
        cancelled: 'Zug ausgefallen',
        actual: 'Tatsächlich',
        noMatchHint: 'Nichts passendes gefunden?',
        manualLink: 'Manuell eingeben',
        skipToManual: 'Manuell weiter',
      },
      reise: {
        title: 'Reisedaten prüfen',
        from: 'Startbahnhof',
        to: 'Zielbahnhof',
        date: 'Reisedatum',
        train: 'Zugnummer',
      },
      problem: {
        title: 'Verspätung oder Problem',
        question: 'Was ist passiert?',
        reiseabbruch: 'Reiseabbruch in Bahnhof',
        reiseunterbrechung: 'Reiseunterbrechung in Bahnhof',
        verpassterAnschluss: 'Verpasster Anschlusszug',
        letzterUmstieg: 'Letzter Umstieg in Bahnhof',
      },
      person: {
        title: 'Persönliche Daten',
        fullName: 'Vor- und Nachname',
        email: 'E-Mail-Adresse',
        telefonOpt: 'Telefonnummer (optional)',
        kundennummerOpt: 'Kundennummer (optional)',
        kundennummerHelper: 'Nur für dein Profil — wird derzeit nicht an die Bahn übermittelt.',
      },
      auszahlung: {
        title: 'Auszahlung',
        kontoinhaber: 'Kontoinhaber',
        iban: 'IBAN',
        bic: 'BIC',
        note: 'Auszahlung nach erfolgreicher Prüfung des Antrags.',
      },
      review: {
        title: 'Bitte prüf deine Angaben',
        edit: 'Bearbeiten',
        ticket: 'Ticket',
        trip: 'Reise',
        problem: 'Problem',
        person: 'Persönliche Daten',
        payout: 'Auszahlung',
        noTicket: 'Kein Ticket hochgeladen',
        submit: 'Antrag absenden',
      },
      submitted: {
        title: 'Antrag eingereicht',
        body: 'Dein Antrag ist auf dem Weg zur Bahn. Wir melden uns, sobald es Rückmeldung gibt.',
        cta: 'Zur Übersicht',
      },
    },
  },
  en: {
    menu: {
      login: 'Log in',
      logout: 'Log out',
      account: 'Account',
      profile: 'Profile',
      faq: 'FAQ',
      prices: 'Pricing',
      support: 'Support',
      legal: 'Legal',
      imprint: 'Imprint',
      back: 'Back',
    },
    hero: {
      claim: 'From Delay to Pay',
      title: 'Train delayed?\nGet your money back!',
      mobileTitle: 'Train delayed?\nGet your money back!',
      sub: 'Skip the paperwork maze. RailBack checks your trip, shows your possible claim and guides you through to payout.',
      mobileSub: 'Upload ticket, check delay and receive compensation.',
      cta1: 'Get compensated!',
      mobileCta: 'Check claim now',
      cta2: 'When do I get money?',
      tag: ['SIMPLE.', 'DIGITAL.', 'STRESS-FREE.'],
      proof: [
        'Upload your ticket',
        'The delay is checked',
        'Receive your compensation',
      ],
      trust: [
        'No claim without your approval',
        'Claim in under 60 seconds',
        'GDPR-compliant from Mannheim',
      ],
      phone: {
        greeting: 'Hello Tobias!',
        overview: 'Here is your trip overview.',
        route: 'Munich → Berlin',
        meta: '24 Jun 2026 • ICE 1232',
        amount: '€24.50',
        amountLabel: 'Expected compensation',
        delay: 'Delay detected · 78 min',
        ticketChecked: 'Ticket checked',
        claimCalculated: 'Claim calculated',
        refundPossible: 'Refund possible',
        refundBasis: 'Based on ticket price and detected delay.',
      },
    },
    eligibility: {
      eyebrow: 'When is compensation possible?',
      title: 'If the railway makes you wait, frustration does not have to be the end of it.',
      lead: 'The amount depends on delay, ticket price and trip situation. RailBack shows what is realistically possible before you file.',
      items: [
        {
          amount: '25%',
          title: 'From 60 minutes at arrival',
          text: 'For many train journeys, a one-hour delay can qualify for a partial ticket refund.',
        },
        {
          amount: '50%',
          title: 'From 120 minutes at arrival',
          text: 'Very long delays can lead to a significantly higher claim.',
        },
        {
          amount: 'Check',
          title: 'Cancellation or missed connection',
          text: 'Cancelled trains and missed connections can also matter. We check your specific journey.',
        },
        {
          amount: 'Clarity',
          title: 'Know before you proceed',
          text: 'You see the possible amount and conditions before any claim is submitted.',
        },
      ],
    },
    faq: {
      title: 'Frequently Asked Questions',
      lead: 'Here you can find answers to the most important questions about RailBack and train refunds.',
      topics: [
        { id: 'ticket', t: 'Ticket & Upload', d: 'How to add your ticket and what we support', icon: 'ticket' },
        { id: 'reise', t: 'Journey & Delay', d: 'How the check works and when you are entitled to compensation', icon: 'clock' },
        { id: 'anspruch', t: 'Claim & Refund', d: 'How the calculation works and what you can expect', icon: 'euro' },
        { id: 'antrag', t: 'Application & Payout', d: 'What happens after approval and when you receive your money', icon: 'checkCircle' },
      ],
    },
    footer: {
      tagline: 'From Delay to Pay.',
      copyright: '© 2026 Elaspix UG · All rights reserved.',
    },
    auth: {
      login: {
        title: 'Login',
        email: 'Email',
        password: 'Password',
        submit: 'Login',
        noAccount: "Don't have an account?",
        register: 'Register',
        error: 'Login failed',
      },
      register: {
        title: 'Register',
        step1Title: 'Personal Information',
        step2Title: 'Address',
        step3Title: 'Bank Details',
        step4Title: 'Confirmation',
        vorname: 'First Name',
        nachname: 'Last Name',
        email: 'Email',
        password: 'Password',
        telefon: 'Phone',
        strasse: 'Street',
        hausnr: 'House Number',
        plz: 'Postal Code',
        ort: 'City',
        land: 'Country',
        iban: 'IBAN',
        bic: 'BIC',
        skipBank: 'Add Later',
        datenschutz: 'I accept the privacy policy',
        agb: 'I accept the terms and conditions',
        next: 'Next',
        back: 'Back',
        submit: 'Register',
        haveAccount: 'Already have an account?',
        login: 'Login',
        error: 'Registration failed',
      },
      profile: {
        title: 'Profile',
        personalTitle: 'Personal Information',
        bankTitle: 'Bank Details',
        accountTitle: 'Account',
        edit: 'Edit',
        save: 'Save',
        cancel: 'Cancel',
        deleteAccount: 'Delete Account',
        deleteConfirm: 'Do you really want to delete your account?',
        confirmPassword: 'Confirm Password',
        updateSuccess: 'Successfully updated',
        updateError: 'Update failed',
      },
    },
    dashboard: {
      heroTitle: 'Train delayed? We help with your compensation!',
      heroSub: 'Upload your ticket, have the delay checked, and get a prepared claim for your compensation.',
      startCta: 'Start refund',
      claimsTitle: 'Claims',
      details: 'Details',
      date: 'Date',
      trip: 'Trip',
      traveler: 'Traveler',
      empty: 'No claims yet — start your first refund above.',
      faq: 'FAQ',
      help: 'Help',
      menu: 'Claims',
    },
    claimDetail: {
      back: 'Back to overview',
      updated: 'Last updated',
      claim: 'Claim',
      antragsart: 'Claim type',
      antragsgrund: 'Reason',
      delay: 'Delay',
      expectedRefund: 'Expected refund',
      trip: 'Trip',
      date: 'Date',
      route: 'Route',
      train: 'Train',
      scheduled: 'Scheduled',
      actual: 'Actual',
      ticketPrice: 'Ticket price',
      traveler: 'Traveler',
      name: 'Name',
      email: 'Email delivery',
      emailStatus: 'Status',
      submittedAt: 'Submitted at',
      timeline: 'Timeline',
    },
    wizard: {
      back: 'Back',
      next: 'Next',
      entry: {
        title: 'Start a claim',
        sub: 'Choose how you want to enter your trip.',
        uploadTitle: 'Upload ticket',
        uploadBody: 'We read the details from your ticket automatically.',
        lookupTitle: 'Search trip',
        lookupBody: 'For regulars — pick the right train quickly.',
        manualTitle: 'Enter manually',
        manualBody: 'Fill in every field yourself — no ticket needed.',
      },
      upload: {
        title: 'Upload ticket',
        hint: 'Upload your ticket as a PDF, JPG or PNG.',
        pick: 'Choose file',
        formats: 'PDF, JPG or PNG',
        maxSize: 'Max file size: {mb} MB',
        removeFile: 'Remove file',
        processing: 'Reading your ticket…',
        processingHint: 'We\'re filling in your trip details automatically.',
      },
      lookup: {
        title: 'Search trip',
        hint: 'Find the trip you want to claim compensation for. We show the delay data from the rail archive.',
        from: 'Origin station',
        to: 'Destination station',
        date: 'Travel date',
        aroundTime: 'around',
        search: 'Search',
        resultsTitle: 'Connections',
        pickHint: 'Pick the trip you actually took.',
        onTime: 'Ran on time',
        minutesLate: 'min late',
        cancelled: 'Train cancelled',
        actual: 'Actual',
        noMatchHint: 'Nothing fits?',
        manualLink: 'Enter manually',
        skipToManual: 'Skip to manual',
      },
      reise: {
        title: 'Check trip data',
        from: 'Origin station',
        to: 'Destination station',
        date: 'Travel date',
        train: 'Train number',
      },
      problem: {
        title: 'Delay or problem',
        question: 'What happened?',
        reiseabbruch: 'Journey cancelled at station',
        reiseunterbrechung: 'Journey interrupted at station',
        verpassterAnschluss: 'Missed connection',
        letzterUmstieg: 'Last transfer at station',
      },
      person: {
        title: 'Personal details',
        fullName: 'First and last name',
        email: 'Email address',
        telefonOpt: 'Phone (optional)',
        kundennummerOpt: 'Customer number (optional)',
        kundennummerHelper: 'For your profile only — not sent to Deutsche Bahn yet.',
      },
      auszahlung: {
        title: 'Payout',
        kontoinhaber: 'Account holder',
        iban: 'IBAN',
        bic: 'BIC',
        note: 'Paid out after your claim is approved.',
      },
      review: {
        title: 'Please review your details',
        edit: 'Edit',
        ticket: 'Ticket',
        trip: 'Trip',
        problem: 'Problem',
        person: 'Personal details',
        payout: 'Payout',
        noTicket: 'No ticket uploaded',
        submit: 'Submit claim',
      },
      submitted: {
        title: 'Claim submitted',
        body: 'Your claim is on its way to Deutsche Bahn. We\'ll let you know as soon as there\'s news.',
        cta: 'Back to overview',
      },
    },
  },
};

const isLanguage = (value: string | null): value is Language => value === 'de' || value === 'en';

const getInitialLanguage = (): Language => {
  const savedLanguage = window.localStorage.getItem('rb_lang');
  return isLanguage(savedLanguage) ? savedLanguage : 'de';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem('rb_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const value = {
    lang,
    setLang: setLangState,
    t: translations[lang],
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
