/**
 * German railway stations the backend can resolve by name.
 *
 * Mirror of backend/lib/src/refund/stations.ts (382 entries — DB category 1-3).
 * Kept in sync manually — if the backend list is regenerated, re-derive
 * this file from it. We only need the names on the frontend; the backend
 * resolves name → eva itself.
 *
 * Used by StationInput for autocomplete suggestions.
 */
export const STATIONS: readonly string[] = [
  "Augsburg Hbf",
  "Berlin Gesundbrunnen",
  "Berlin Hauptbahnhof",
  "Berlin Ostbahnhof",
  "Berlin Südkreuz",
  "Dortmund Hbf",
  "Dresden Hbf",
  "Duisburg Hbf",
  "Düsseldorf Hbf",
  "Essen Hbf",
  "Frankfurt (Main) Hbf",
  "Hamburg Hbf",
  "Hamburg-Altona",
  "Hannover Hbf",
  "Karlsruhe Hbf",
  "Köln Hbf",
  "Köln Messe/Deutz",
  "Leipzig Hbf",
  "Mannheim Hbf",
  "München Hbf",
  "München Ost",
  "Nürnberg Hbf",
  "Stuttgart Hbf",
  "Aachen Hbf",
  "Aschaffenburg Hbf",
  "Bad Oldesloe",
  "Bamberg",
  "Berlin Friedrichstraße",
  "Berlin Ostkreuz",
  "Berlin Potsdamer Platz",
  "Berlin Zoologischer Garten",
  "Berlin-Lichtenberg",
  "Berlin-Spandau",
  "Berlin-Wannsee",
  "Bielefeld Hbf",
  "Bietigheim-Bissingen",
  "Bochum Hbf",
  "Bonn Hbf",
  "Braunschweig Hbf",
  "Bremen Hbf",
  "Bruchsal",
  "Chemnitz Hbf",
  "Cottbus Hbf",
  "Darmstadt Hbf",
  "Dresden-Neustadt",
  "Erfurt Hbf",
  "Flughafen BER",
  "Frankfurt (Main) Süd",
  "Frankfurt (Oder)",
  "Freiburg (Breisgau) Hbf",
  "Fulda",
  "Fürth (Bay) Hbf",
  "Gelsenkirchen Hbf",
  "Gießen",
  "Göttingen",
  "Hagen Hbf",
  "Halle (Saale) Hbf",
  "Hamburg Dammtor",
  "Hamburg-Harburg",
  "Hamm (Westf) Hbf",
  "Hanau Hbf",
  "Heidelberg Hbf",
  "Herford",
  "Hildesheim Hbf",
  "Ingolstadt Hbf",
  "Kaiserslautern Hbf",
  "Kassel Hbf",
  "Kassel-Wilhelmshöhe",
  "Kiel Hbf",
  "Koblenz Hbf",
  "Landshut (Bay) Hbf",
  "Ludwigshafen (Rhein) Hbf",
  "Lübeck Hbf",
  "Lüneburg",
  "Magdeburg Hbf",
  "Mainz Hbf",
  "Mönchengladbach Hbf",
  "München-Pasing",
  "Münster (Westf) Hbf",
  "Neumünster",
  "Neuss Hbf",
  "Neustadt (Weinstr) Hbf",
  "Oberhausen Hbf",
  "Offenburg",
  "Oldenburg (Oldb) Hbf",
  "Osnabrück Hbf",
  "Paderborn Hbf",
  "Pforzheim Hbf",
  "Plochingen",
  "Potsdam Hbf",
  "Regensburg Hbf",
  "Rheine",
  "Rosenheim",
  "Rostock Hbf",
  "Saarbrücken Hbf",
  "Singen (Hohentwiel)",
  "Solingen Hbf",
  "Trier Hbf",
  "Tübingen Hbf",
  "Uelzen",
  "Ulm Hbf",
  "Weimar",
  "Wiesbaden Hbf",
  "Wolfsburg Hbf",
  "Worms Hbf",
  "Wuppertal Hbf",
  "Würzburg Hbf",
  "Aalen Hbf",
  "Altbach",
  "Altenbeken",
  "Alzey",
  "Andernach",
  "Angermünde",
  "Ansbach",
  "Au (Sieg)",
  "Augsburg Haunstetterstraße",
  "Augsburg-Hochzoll",
  "Backnang",
  "Bad Friedrichshall Hbf",
  "Bad Hersfeld",
  "Bad Homburg",
  "Bad Kreuznach",
  "Bad Oeynhausen",
  "Bad Schandau",
  "Bad Vilbel",
  "Baden-Baden",
  "Bayreuth Hbf",
  "Bebra",
  "Bergen auf Rügen",
  "Berlin Alexanderplatz",
  "Berlin Anhalter Bahnhof",
  "Berlin Bornholmer Straße",
  "Berlin Frankfurter Allee",
  "Berlin Olympiastadion",
  "Berlin Westkreuz",
  "Berlin-Charlottenburg",
  "Berlin-Hohenschönhausen",
  "Berlin-Lichterfelde Ost",
  "Berlin-Mahlsdorf",
  "Berlin-Neukölln",
  "Berlin-Schöneweide",
  "Berliner Tor",
  "Bernau (b Berlin)",
  "Betzdorf (Sieg)",
  "Bitterfeld",
  "Blankenese",
  "Bonn-Bad Godesberg",
  "Brandenburg Hbf",
  "Bremerhaven Hbf",
  "Buchholz (Nordheide)",
  "Buchloe",
  "Bullay (DB)",
  "Buxtehude",
  "Böblingen",
  "Büchen",
  "Bünde (Westf)",
  "Castrop-Rauxel Hbf",
  "Celle Pbf",
  "Coburg",
  "Crailsheim",
  "Dachau Bahnhof",
  "Delmenhorst",
  "Dessau Hbf",
  "Dortmund-Dorstfeld",
  "Düren",
  "Düsseldorf Flughafen",
  "Düsseldorf-Benrath",
  "Düsseldorf-Derendorf",
  "Eberbach",
  "Eberswalde Hbf",
  "Eidelstedt",
  "Eisenach Hbf",
  "Elmshorn",
  "Emden Hbf",
  "Erkner",
  "Erlangen",
  "Esslingen (Neckar)",
  "Esslingen-Mettingen",
  "Esslingen-Zell",
  "Euskirchen",
  "Falkenberg (Elster)",
  "Fellbach",
  "Feucht",
  "Finnentrop",
  "Flensburg",
  "Frankenthal Hbf",
  "Frankfurt (Main) Flughafen Regionalbahnhof",
  "Frankfurt (Main) Hauptwache",
  "Frankfurt (Main) Konstablerwache",
  "Frankfurt (Main) Niederrad",
  "Frankfurt (Main) Ostendstraße",
  "Frankfurt (Main) Stadion",
  "Frankfurt (Main) Taunusanlage",
  "Frankfurt (Main) West",
  "Frankfurt am Main Flughafen Fernbahnhof",
  "Frankfurt-Höchst",
  "Frankfurt-Rödelheim",
  "Freilassing",
  "Freising",
  "Friedberg (Hess)",
  "Friedrichshafen Stadt",
  "Fröndenberg",
  "Garmisch-Partenkirchen",
  "Geltendorf",
  "Gera Hbf",
  "Germering-Unterpfaffenhofen",
  "Glauchau (Sachs)",
  "Goslar",
  "Gotha",
  "Graben-Neudorf",
  "Grafing Bahnhof",
  "Greven",
  "Groß Gerau-Dornberg",
  "Göppingen",
  "Görlitz",
  "Günzburg",
  "Güstrow",
  "Gütersloh Hbf",
  "Halberstadt Hbf",
  "Hamburg-Bergedorf",
  "Hamburg-Neugraben",
  "Hameln",
  "Hannover-Messe / Laatzen",
  "Harburg Rathaus",
  "Hasselbrook",
  "Heide (Holst)",
  "Heilbronn Hbf",
  "Hennef (Sieg)",
  "Hennigsdorf (b Berlin)",
  "Herne",
  "Herne-Wanne-Eickel Hbf",
  "Herrenberg",
  "Herzogenrath",
  "Hof Hbf",
  "Hofheim (Taunus)",
  "Holzkirchen",
  "Homburg (Saar) Hbf",
  "Horb",
  "Horrem",
  "Husum",
  "Ingolstadt Nord",
  "Itzehoe",
  "Jena Paradies",
  "Jena West",
  "Jena-Göschwitz",
  "Karlsruhe-Durlach",
  "Kempten (Allgäu) Hbf",
  "Konstanz",
  "Kornwestheim Pbf",
  "Krefeld Hbf",
  "Köln-Ehrenfeld",
  "Köln-Mülheim",
  "Köln/Bonn Flughafen",
  "Königs Wusterhausen",
  "Köthen",
  "Landstuhl",
  "Langenhagen-Mitte",
  "Leer (Ostfriesl)",
  "Lehrte",
  "Leinefelde",
  "Leipzig Messe",
  "Leonberg",
  "Lichtenfels",
  "Limburg (Lahn)",
  "Lindau-Insel",
  "Lindau-Reutin",
  "Ludwigsburg",
  "Ludwigshafen (Rhein) Mitte",
  "Lutherstadt Wittenberg Hbf",
  "Mainz Römisches Theater",
  "Mainz-Gustavsburg",
  "Marbach (Neckar)",
  "Marburg (Lahn)",
  "Marktredwitz",
  "Memmingen",
  "Mering",
  "Merzig (Saar)",
  "Minden (Westf)",
  "Mosbach-Neckarelz",
  "Mühlacker",
  "Mülheim (Ruhr) Hbf",
  "Mülheim (Ruhr)-Styrum",
  "München Donnersbergerbrücke",
  "München Karlsplatz",
  "München Marienplatz",
  "München Rosenheimer Platz",
  "München-Giesing",
  "München-Hackerbrücke",
  "München-Hirschgarten",
  "München-Laim Pbf",
  "Nauen",
  "Naumburg (Saale) Hbf",
  "Neckargemünd",
  "Neu-Edingen/Friedrichsfeld",
  "Neudietendorf",
  "Neumarkt (Oberpf)",
  "Neunkirchen (Saar) Hbf",
  "Neuwied",
  "Niebüll",
  "Nienburg (Weser)",
  "Nordhausen",
  "Northeim (Han)",
  "Nürtingen",
  "Oberesslingen",
  "Oberstdorf",
  "Offenbach (Main) Ost",
  "Opladen",
  "Oranienburg",
  "Ostseebad Binz",
  "Passau Hbf",
  "Petershausen (Oberbay)",
  "Pinneberg",
  "Plattling",
  "Plauen (Vogtl) ob Bf",
  "Potsdam Park Sanssouci",
  "Radolfzell",
  "Rastatt",
  "Recklinghausen Hbf",
  "Remagen",
  "Rendsburg",
  "Renningen",
  "Reutlingen Hbf",
  "Rheda-Wiedenbrück",
  "Riesa",
  "Roth",
  "Rottweil",
  "Rüsselsheim",
  "Saalfeld (Saale)",
  "Saarlouis Hbf",
  "Schifferstadt",
  "Schorndorf",
  "Schwabach",
  "Schweinfurt Hbf",
  "Schwelm",
  "Schwerin Hbf",
  "Schönebeck (Elbe)",
  "Schönefeld (bei Berlin)",
  "Siegburg/Bonn",
  "Siegen Hbf",
  "Soest",
  "St. Ingbert",
  "Stendal Hbf",
  "Sternschanze",
  "Stralsund Hbf",
  "Straubing",
  "Stuttgart Feuersee",
  "Stuttgart Schwabstraße",
  "Stuttgart Stadtmitte",
  "Stuttgart-Bad Cannstatt",
  "Stuttgart-Feuerbach",
  "Stuttgart-Untertürkheim Pbf",
  "Stuttgart-Vaihingen",
  "Stuttgart-Zuffenhausen",
  "Traunstein",
  "Treuchtlingen",
  "Troisdorf",
  "Tuttlingen",
  "Tutzing",
  "Unna",
  "Verden (Aller)",
  "Viersen",
  "Völklingen",
  "Waiblingen",
  "Waren (Müritz)",
  "Warnemünde",
  "Weiden (Oberpf)",
  "Weil am Rhein",
  "Weilheim (Oberbay)",
  "Weinheim (Bergstr) Hbf",
  "Weißenfels",
  "Wendlingen (Neckar)",
  "Wesel",
  "Westerland (Sylt)",
  "Wetzlar",
  "Wiesloch-Walldorf",
  "Winnenden",
  "Witten Hbf",
  "Wittenberge",
  "Wunstorf",
  "Wuppertal-Oberbarmen",
  "Wuppertal-Vohwinkel",
  "Zwickau (Sachs) Hbf",
];
